version: "3.9"
services:
  app:
    build:
      args:
        user: jamessoncardozo
        uid: 1000
        gid: 1000
        Country: BR
        State: São Paulo
        Locality: Development Laboratory
        Organization: Qualquer 
        OrganizationalUnit: 
        CommonName: ${HOSTNAME}
        EmailAddress: youradress@example.com

      context: ./
      dockerfile: Dockerfile
    container_name: vcard-app
    restart: unless-stopped
    working_dir: /var/www/virtual-card
    volumes:
      - ./:/var/www/virtual-card
    networks:
      - vcard-net

  db:
    image: mysql:latest
    container_name: vcard-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - vcard-net

  nginx:
    image: nginx:alpine
    container_name: vcard-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/virtual-card
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - vcard-net
networks:
  vcard-net:
    driver: bridge